import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const cx5 = await prisma.car.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      modelName: "CX-5",
      modelCode: "6BA-EKEP",
      gradeName: "20S Smart Edition",
      makerName: "マツダ",
      powerTrain: "ICE",
      driveSystem: "AWD",
      url: "https://www.mazda.co.jp/cars/cx-5/",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/8/85/2017_Mazda_CX-5_%28KF%29_Maxx_2WD_wagon_%282018-11-02%29_01.jpg",
      price: 3200000,
      bodyType: "SUV",
      bodyLength: 4747,
      bodyWidth: 1850,
      bodyHeight: 1690,
      wheelBase: 2700,
      treadFront: 1590,
      treadRear: 1590,
      roadClearance: 200,
      weight: 1550,
      interiorLength: 1890,
      interiorWidth: 1540,
      interiorHeight: 1265,
      ridingCap: 5,
      steering: "ラック&ピニオン式",
      suspensionFront: "ストラット式",
      suspensionRear: "マルチリンク式",
      breakFront: "ベンチレーテッドディスク",
      breakRear: "ディスク",
      engineCode: "PE-VPS",
      engineType: "水冷直列4気筒DOHC16バルブ",
      cylinderNum: 4,
      cylinderLayout: "直列",
      valveSystem: "DOHC",
      displacement: 1997,
      bore: 83.5,
      stroke: 91.2,
      compressionRatio: 13.0,
      maxOutputKw: 115,
      maxOutputLowerRpm: 6000,
      maxOutputHigherRpm: 4000,
      maxTorqueNm: 213,
      maxTorqueLowerRpm: 4000,
      maxTorqueHigherRpm: 4000,
      fuelSystem: "筒内直接噴射(DI)",
      fuelType: "REGULAR",
      fuelTankCap: 56,
      fcrWltc: 14.6,
      fcrWltcL: 11.2,
      fcrWltcM: 15.3,
      fcrWltcH: 16.2,
      fcrJc08: 15.6,
      minTurningRadius: 5.5,
      fuelEfficiency: [
        "ミラーサイクルエンジン",
        "アイドリングストップ機構",
        "筒内直接噴射(DI)",
        "可変バルブタイミング",
        "気筒休止(PY-RPS型車)",
        "充電制御",
        "ロックアップ機構付トルクコンバーター",
        "電動パワーステアリング",
      ],
    },
  });
  console.log({ cx5 });

  const corolla = await prisma.car.upsert({
    where: { id: 2 },
    update: {},
    create: {
      id: 2,
      modelName: "カローラツーリング",
      modelCode: "6AA-XWE211-AEXSB",
      gradeName: "WxB",
      makerName: "トヨタ",
      powerTrain: "StrHV",
      driveSystem: "AWD",
      url: "https://toyota.jp/corollatouring/",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/8/8a/Toyota_COROLLA_TOURING_HYBRID_W%C3%97B_2WD_%286AA-ZWE211W-AWXSB%29_front.jpg",
      price: 2678500,
      bodyType: "STATION_WAGON",
      bodyLength: 4495,
      bodyWidth: 1745,
      bodyHeight: 1460,
      wheelBase: 2700,
      treadFront: 1590,
      treadRear: 1590,
      roadClearance: 200,
      weight: 1550,
      interiorLength: 1890,
      interiorWidth: 1540,
      interiorHeight: 1265,
      ridingCap: 5,
      steering: "ラック&ピニオン式",
      suspensionFront: "ストラット式",
      suspensionRear: "マルチリンク式",
      breakFront: "ベンチレーテッドディスク",
      breakRear: "ディスク",
      engineCode: "PE-VPS",
      engineType: "水冷直列4気筒DOHC16バルブ",
      cylinderNum: 4,
      cylinderLayout: "直列",
      valveSystem: "DOHC",
      displacement: 1997,
      bore: 83.5,
      stroke: 91.2,
      compressionRatio: 13.0,
      maxOutputKw: 115,
      maxOutputLowerRpm: 6000,
      maxOutputHigherRpm: 4000,
      maxTorqueNm: 213,
      maxTorqueLowerRpm: 4000,
      maxTorqueHigherRpm: 4000,
      fuelSystem: "筒内直接噴射(DI)",
      fuelType: "REGULAR",
      fuelTankCap: 56,
      fcrWltc: 14.6,
      fcrWltcL: 11.2,
      fcrWltcM: 15.3,
      fcrWltcH: 16.2,
      fcrJc08: 15.6,
      minTurningRadius: 5.5,
      fuelEfficiency: [
        "ミラーサイクルエンジン",
        "アイドリングストップ機構",
        "筒内直接噴射(DI)",
        "可変バルブタイミング",
        "気筒休止(PY-RPS型車)",
        "充電制御",
        "ロックアップ機構付トルクコンバーター",
        "電動パワーステアリング",
      ],
    },
  });

  const nsx = await prisma.car.upsert({
    where: { id: 3 },
    update: {},
    create: {
      id: 3,
      modelName: "NSX",
      modelCode: "5AA-NC1",
      gradeName: "Type S",
      makerName: "ホンダ",
      powerTrain: "MldHV",
      driveSystem: "AWD",
      url: "https://www.honda.co.jp/NSX/types/",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/e/ea/2019_Honda_NSX_3.5_CAA-NC1_%2820190722%29_01.jpg",
      price: 27940000,
      bodyType: "COUPE",
      bodyLength: 4535,
      bodyWidth: 1940,
      bodyHeight: 1215,
      wheelBase: 2700,
      treadFront: 1590,
      treadRear: 1590,
      roadClearance: 200,
      weight: 1550,
      interiorLength: 1890,
      interiorWidth: 1540,
      interiorHeight: 1265,
      ridingCap: 5,
      steering: "ラック&ピニオン式",
      suspensionFront: "ストラット式",
      suspensionRear: "マルチリンク式",
      breakFront: "ベンチレーテッドディスク",
      breakRear: "ディスク",
      engineCode: "PE-VPS",
      engineType: "水冷直列4気筒DOHC16バルブ",
      cylinderNum: 4,
      cylinderLayout: "直列",
      valveSystem: "DOHC",
      displacement: 1997,
      bore: 83.5,
      stroke: 91.2,
      compressionRatio: 13.0,
      maxOutputKw: 115,
      maxOutputLowerRpm: 6000,
      maxOutputHigherRpm: 4000,
      maxTorqueNm: 213,
      maxTorqueLowerRpm: 4000,
      maxTorqueHigherRpm: 4000,
      fuelSystem: "筒内直接噴射(DI)",
      fuelType: "PREMIUM",
      fuelTankCap: 56,
      fcrWltc: 14.6,
      fcrWltcL: 11.2,
      fcrWltcM: 15.3,
      fcrWltcH: 16.2,
      fcrJc08: 15.6,
      minTurningRadius: 5.5,
      fuelEfficiency: [
        "ミラーサイクルエンジン",
        "アイドリングストップ機構",
        "筒内直接噴射(DI)",
        "可変バルブタイミング",
        "気筒休止(PY-RPS型車)",
        "充電制御",
        "ロックアップ機構付トルクコンバーター",
        "電動パワーステアリング",
      ],
    },
  });

  const hondae = await prisma.car.upsert({
    where: { id: 4 },
    update: {},
    create: {
      id: 4,
      modelName: "Honda e",
      modelCode: "ZAA-ZC7",
      gradeName: "Advance",
      makerName: "ホンダ",
      powerTrain: "BEV",
      driveSystem: "RR",
      url: "https://www.honda.co.jp/honda-e/",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/9/9e/Honda_e_Advance_%28ZAA-ZC7%29_front.jpg",
      price: 4950000,
      bodyType: "HATCHBACK",
      bodyLength: 3895,
      bodyWidth: 1750,
      bodyHeight: 1510,
      wheelBase: 2700,
      treadFront: 1590,
      treadRear: 1590,
      roadClearance: 200,
      weight: 1550,
      interiorLength: 1890,
      interiorWidth: 1540,
      interiorHeight: 1265,
      ridingCap: 5,
      steering: "ラック&ピニオン式",
      suspensionFront: "ストラット式",
      suspensionRear: "マルチリンク式",
      breakFront: "ベンチレーテッドディスク",
      breakRear: "ディスク",
      engineCode: "PE-VPS",
      engineType: "水冷直列4気筒DOHC16バルブ",
      cylinderNum: 4,
      cylinderLayout: "直列",
      valveSystem: "DOHC",
      displacement: 1997,
      bore: 83.5,
      stroke: 91.2,
      compressionRatio: 13.0,
      maxOutputKw: 115,
      maxOutputLowerRpm: 6000,
      maxOutputHigherRpm: 4000,
      maxTorqueNm: 213,
      maxTorqueLowerRpm: 4000,
      maxTorqueHigherRpm: 4000,
      fuelSystem: "筒内直接噴射(DI)",
      fuelType: "PREMIUM",
      fuelTankCap: 56,
      fcrWltc: 14.6,
      fcrWltcL: 11.2,
      fcrWltcM: 15.3,
      fcrWltcH: 16.2,
      fcrJc08: 15.6,
      minTurningRadius: 5.5,
      fuelEfficiency: [
        "ミラーサイクルエンジン",
        "アイドリングストップ機構",
        "筒内直接噴射(DI)",
        "可変バルブタイミング",
        "気筒休止(PY-RPS型車)",
        "充電制御",
        "ロックアップ機構付トルクコンバーター",
        "電動パワーステアリング",
      ],
    },
  });

  const note = await prisma.car.upsert({
    where: { id: 5 },
    update: {},
    create: {
      id: 5,
      modelName: "ノート",
      modelCode: "HR15DE",
      gradeName: "15RX",
      makerName: "日産",
      powerTrain: "SerHV",
      driveSystem: "FF",
      url: "https://www3.nissan.co.jp/vehicles/new/note.html",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/0/0a/Nissan_Note_e-POWER_%28E13%29%2C_2021%2C_front-left.jpg",
      price: 2445300,
      bodyType: "HATCHBACK",
      bodyLength: 4045,
      bodyWidth: 1695,
      bodyHeight: 1520,
      wheelBase: 2700,
      treadFront: 1590,
      treadRear: 1590,
      roadClearance: 200,
      weight: 1550,
      interiorLength: 1890,
      interiorWidth: 1540,
      interiorHeight: 1265,
      ridingCap: 5,
      steering: "ラック&ピニオン式",
      suspensionFront: "ストラット式",
      suspensionRear: "マルチリンク式",
      breakFront: "ベンチレーテッドディスク",
      breakRear: "ディスク",
      engineCode: "PE-VPS",
      engineType: "水冷直列4気筒DOHC16バルブ",
      cylinderNum: 4,
      cylinderLayout: "直列",
      valveSystem: "DOHC",
      displacement: 1997,
      bore: 83.5,
      stroke: 91.2,
      compressionRatio: 13.0,
      maxOutputKw: 115,
      maxOutputLowerRpm: 6000,
      maxOutputHigherRpm: 4000,
      maxTorqueNm: 213,
      maxTorqueLowerRpm: 4000,
      maxTorqueHigherRpm: 4000,
      fuelSystem: "筒内直接噴射(DI)",
      fuelType: "REGULAR",
      fuelTankCap: 56,
      fcrWltc: 14.6,
      fcrWltcL: 11.2,
      fcrWltcM: 15.3,
      fcrWltcH: 16.2,
      fcrJc08: 15.6,
      minTurningRadius: 5.5,
      fuelEfficiency: [
        "ミラーサイクルエンジン",
        "アイドリングストップ機構",
        "筒内直接噴射(DI)",
        "可変バルブタイミング",
        "気筒休止(PY-RPS型車)",
        "充電制御",
        "ロックアップ機構付トルクコンバーター",
        "電動パワーステアリング",
      ],
    },
  });

  const series3 = await prisma.car.upsert({
    where: { id: 6 },
    update: {},
    create: {
      id: 6,
      modelName: "3シリーズツーリング",
      modelCode: "3BA-6K20",
      gradeName: "318iツーリング",
      makerName: "BMW",
      powerTrain: "ICE",
      driveSystem: "AWD",
      url: "https://www.bmw.co.jp/ja/all-models/3-series/touring/2019/bmw-3-series-touring-inspire.html",
      imageUrl: "",
      price: 6340000,
      bodyType: "STATION_WAGON",
      bodyLength: 4715,
      bodyWidth: 1825,
      bodyHeight: 1475,
      wheelBase: 2700,
      treadFront: 1590,
      treadRear: 1590,
      roadClearance: 200,
      weight: 1550,
      interiorLength: 1890,
      interiorWidth: 1540,
      interiorHeight: 1265,
      ridingCap: 5,
      steering: "ラック&ピニオン式",
      suspensionFront: "ストラット式",
      suspensionRear: "マルチリンク式",
      breakFront: "ベンチレーテッドディスク",
      breakRear: "ディスク",
      engineCode: "PE-VPS",
      engineType: "水冷直列4気筒DOHC16バルブ",
      cylinderNum: 4,
      cylinderLayout: "直列",
      valveSystem: "DOHC",
      displacement: 1997,
      bore: 83.5,
      stroke: 91.2,
      compressionRatio: 13.0,
      maxOutputKw: 115,
      maxOutputLowerRpm: 6000,
      maxOutputHigherRpm: 4000,
      maxTorqueNm: 213,
      maxTorqueLowerRpm: 4000,
      maxTorqueHigherRpm: 4000,
      fuelSystem: "筒内直接噴射(DI)",
      fuelType: "DIESEL",
      fuelTankCap: 56,
      fcrWltc: 14.6,
      fcrWltcL: 11.2,
      fcrWltcM: 15.3,
      fcrWltcH: 16.2,
      fcrJc08: 15.6,
      minTurningRadius: 5.5,
      fuelEfficiency: [
        "ミラーサイクルエンジン",
        "アイドリングストップ機構",
        "筒内直接噴射(DI)",
        "可変バルブタイミング",
        "気筒休止(PY-RPS型車)",
        "充電制御",
        "ロックアップ機構付トルクコンバーター",
        "電動パワーステアリング",
      ],
    },
  });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
