name: deploy-docs
on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-docs:
    if: ${{ github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prd' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm install
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_DOCS_ROLE_ARN }}
          role-session-name: "mincuru-deploy-docs-session"
          aws-region: ap-northeast-1
      - name: Build next.js
        run: |
          npm run build -w apps/docs
      - name: Deploy docs
        run: |
          aws s3 sync ./apps/docs/dist s3://${{ secrets.AWS_S3_DOCS_BUCKET_NAME }}
