name: Pipeline
on:
  push:

permissions:
  id-token: write
  contents: read

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

jobs:
  test:
    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/mincuru?schema=public
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TEST_ROLE_ARN }}
          aws-region: ap-northeast-1
      - run: npm run db:generate -w packages/database
      - run: npm run db:migrate -w packages/database
      - run: npm run db:seed -w packages/database
      - run: npx playwright install
      - run: npm run test -w apps/web
      - run: npm run test:cov -w apps/api
      - run: npm run test -w apps/batch
      - name: Describe distribution
        id: describe-distribution
        run: echo "distribution=$(aws cloudfront list-distributions | jq -r '.DistributionList.Items[] | select(.Origins.Items[] | .DomainName | contains("mincuru-coverage-report")) | .DomainName')" >> $GITHUB_OUTPUT
      - name: Upload coverage to S3
        run: |
          aws s3 sync ./apps/web/coverage s3://${{ secrets.AWS_S3_COVERAGEREPORT_BUCKET_NAME }}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}/web/${{ github.sha }}/ --delete
          echo "* [カバレッジレポート web](https://${{ steps.describe-distribution.outputs.distribution }}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}/web/${{ github.sha }}/index.html)" >> $GITHUB_STEP_SUMMARY
          aws s3 sync ./apps/api/coverage/lcov-report s3://${{ secrets.AWS_S3_COVERAGEREPORT_BUCKET_NAME }}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}/api/${{ github.sha }}/ --delete
          echo "* [カバレッジレポート api](https://${{ steps.describe-distribution.outputs.distribution }}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}/api/${{ github.sha }}/index.html)" >> $GITHUB_STEP_SUMMARY
  deploy-infra:
    if: ${{ github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prd' }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: dorny/paths-filter@v3
      #   id: filter
      #   with:
      #     filters: |
      #       infra:
      #         - 'apps/infra/**'
      - name: Configure AWS Credentials
        # if: steps.filter.outputs.infra == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: "mincuru-deploy-infra-session"
          aws-region: ap-northeast-1
      - name: Install cdk
        # if: steps.filter.outputs.infra == 'true'
        run: |
          npm install -g aws-cdk
          npm install
      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed 's|refs/heads/||')" >> $GITHUB_ENV
      - name: Diff infra
        # if: steps.filter.outputs.infra == 'true'
        run: |
          result=$(npm run cdk -w apps/infra -- diff -c environment=$BRANCH_NAME)
          IFS=$'\n'
          echo '```' >> $GITHUB_STEP_SUMMARY
          for line in $result
          do
            echo -e $line >> $GITHUB_STEP_SUMMARY
          done
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Deploy infra
        # if: steps.filter.outputs.infra == 'true'
        run: |
          npm run cdk -w apps/infra -- deploy InfraStack --require-approval never -c environment=$BRANCH_NAME
  migrate:
    if: ${{ github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prd' }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      # - uses: docker/setup-buildx-action@v2
      # - uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: "mincuru-migrate-session"
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      # - uses: docker/login-action@v2
      #   with:
      #     registry: ${{ secrets.ECR_REGISTRY }}
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mincuru/migrate
          IMAGE_TAG: latest
        run: |
          docker build -f ./apps/migrate/docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Describe public subnet
        id: describe-subnet
        run: echo "public_subnet=$(aws ec2 describe-subnets --filters Name=tag:Name,Values=InfraStack/Vpc/Vpc/PublicSubnet1 --query 'Subnets[0].SubnetId' --output text)" >> $GITHUB_OUTPUT
      - name: Describe source security group
        id: describe-security-group
        run: echo "source_security_group=$(aws ec2 describe-security-groups --filters Name=group-name,Values=SourceSecurityGroup --query 'SecurityGroups[0].GroupId' --output text)" >> $GITHUB_OUTPUT
      - name: Run Migration
        run: |
          aws ecs run-task \
            --cluster MigrateCluster \
            --task-definition MigrateTaskDefinition \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[${{ steps.describe-subnet.outputs.public_subnet }}],securityGroups=[${{ steps.describe-security-group.outputs.source_security_group }}],assignPublicIp=ENABLED}"
  deploy-web:
    if: ${{ github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prd' }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: "mincuru-deploy-web-session"
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mincuru/web
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID --build-arg GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET --build-arg AUTH_SECRET=$AUTH_SECRET -f ./apps/web/docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition WebTaskDefinition --query taskDefinition > task-definition.json
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: WebContainer
          image: ${{ steps.build-image.outputs.image }}
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: WebService
          cluster: WebCluster
          wait-for-service-stability: true
  deploy-api:
    if: ${{ github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prd' }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: "mincuru-deploy-api-session"
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mincuru/api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f ./apps/api/docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code --function-name mincuru-api --image-uri ${{ steps.build-image.outputs.image }}
  deploy-batch:
    if: ${{ github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prd' }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: "mincuru-deploy-batch-session"
          aws-region: ap-northeast-1
      - name: Deploy lambda
        run: |
          npm run build -w apps/batch
          aws lambda update-function-code --function-name mincuru-batch --zip-file fileb://apps/batch/dist/mincuru-batch.zip --publish --query Version --output text
  deploy-docs:
    if: ${{ github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/prd' }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_DOCS_ROLE_ARN }}
          role-session-name: "mincuru-deploy-docs-session"
          aws-region: ap-northeast-1
      - name: Build next.js
        run: |
          npm run build -w apps/docs
      - name: Deploy docs
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_DOCS_BUCKET_NAME }}
