name: Pipeline
on:
  push:

env:
  AWS_CLOUDFRONT_DISTRIBUTION_NAME: d15dl6nco69pbe.cloudfront.net
  MIGRATE_ECR_REPOSITORY: mincuru/migrate
  MIGRATE_TASK_DEFINITION: MigrateTaskDefinition
  MIGRATE_CONTAINER_NAME: MigrateContainer
  MIGRATE_ECS_SERVICE: MigrateService
  MIGRATE_ECS_CLUSTER: MigrateCluster

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - run: npm run db:generate -w packages/database
      - run: npm run test:coverage -w apps/web
      - name: Upload coverage to S3
        run: |
          aws s3 sync ./apps/web/coverage s3://${{ secrets.AWS_S3_COVERAGEREPORT_BUCKET_NAME }}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}/${{ github.sha }}/ --delete
          echo "* [カバレッジレポート](https://${{ env.AWS_CLOUDFRONT_DISTRIBUTION_NAME }}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}/${{ github.sha }}/index.html)" >> $GITHUB_STEP_SUMMARY
  migrate:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: "mincuru-deploy-session"
          aws-region: ap-northeast-1

      # # ECR ログイン
      # - uses: aws-actions/amazon-ecr-login@v1
      #   id: login-ecr # outputs で参照するために id を設定
      # # Docker イメージを build・push する
      # - name: build and push docker image to ecr
      #   env:
      #     # ECR レジストリを `aws-actions/amazon-ecr-login` アクションの `outputs.registry` から取得
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     # イメージを push する ECR リポジトリ名
      #     # REPOSITORY: ${{ env.MIGRATE_ECR_REPOSITORY }}
      #     # 任意のイメージタグ
      #     # 今回は Git のコミットハッシュにしておく
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -f ./apps/migrate/docker/Dockerfile --tag ${{ secrets.ECR_REGISTRY }}/${{ env.MIGRATE_ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
      #     docker push ${{ secrets.ECR_REGISTRY }}/${{ env.MIGRATE_ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
      - name: Build and push to Migrate ECR
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./apps/migrate/docker/Dockerfile
          tags: ${{ secrets.ECR_REGISTRY }}/${{ env.MIGRATE_ECR_REPOSITORY }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Run Migration
        uses: noelzubin/aws-ecs-run-task@v1.0
        with:
          cluster: ${{ env.MIGRATE_ECS_CLUSTER }}
          task-definition: ${{ env.MIGRATE_TASK_DEFINITION}}
          subnets: ${{ secrets.PRIVATE_SUBNET }}
          security-groups: ${{ secrets.MIGRATE_SECURITY_GROUP }}
          assign-public-ip: ENABLED
          override-container: ${{ env.MIGRATE_CONTAINER_NAME }}
